### ISSUE TITLE
Allow multiple keyvault urls to be used

### ISSUE THREAD

**Issue by fbufler** [mkah91/azure-keyvault-cli#8]
## Story 

As a user I want to keep track of secrets from multiple vaults without reseting the vault url every time.

## Ideas

- Allow the user to add vault urls indexed by a key (e.g. default, user-secrets, admin-secrets, ...) that can be used to query secrets
  - Have a default vault set and allow overriding it with e.g. `azkv --vault <index> ...`
  - Or querying all added vaults when using `azkv ...`
  - Or do both
 
## AC

- [ ] The user is able to persist multiple keyvaults
- [ ] The user is able to query secrets from the persisted vaults

**Comment by fbufler** [comment]
@mkah91 wdyt?

**Comment by mkah91** [comment]
Sounds good. It would be nice to have some nested structure to so that it is always visible in which keyvault you are in but at the same time be able to search in all of them at once.
